### ISSUE TITLE
Add correct identificators for OpenIntranet warehouse

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/SATABAL01#1]
Přidat správná označení [UST_ID](https://github.com/UniversalScientificTechnologies/OpenIntranet/wiki/KiCAD) k použitým součástkám.

**Comment by kaklik** [comment]
Provedeno. Ke konstrole @ChroustJan

**Comment by ChroustJan** [comment]
Přiřazení mi přijde v pořádku.
